name: Auto 48H EPG

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requests
      - run: python update_epg.py
      - run: |
          git config user.name "epg-bot"
          git config user.email "epg@bot.com"
          git add epg.xml
          git commit -m "48h EPG auto update" || true
          git push
